export { default as BajaActivosForm } from "../../components/formatos/BajaActivo/BajaActivo";
export { default as ListabajaAtivos } from "../../components/formatos/BajaActivo/ListaBajaActivo";
export { generarBajaPDF } from "../../components/formatos/BajaActivo/BajaActivoPDF";
export { default as HojaResponsabilidad } from "../../components/formatos/HojaResponsabilidad/HojaResponsabilidad";
export { default as ListaHojasResponsabilidad } from "../../components/formatos/HojaResponsabilidad/ListaHojaResponsabilidad";
export { default as HojaResponsabilidadEdit } from "../../components/formatos/HojaResponsabilidad/HojaResponsabilidadEditar";
export { default as ListaHojaSolvencia } from "../../components/formatos/HojaSolvencia/ListaHojaSolvencia";
export { default as HojaSolvencia } from "../../components/formatos/HojaSolvencia/HojaSolvencia";
export { default as CrearTraslado } from "../../components/formatos/Traslados/Traslados";
export { default as TrasladosLista } from "../../components/formatos/Traslados/ListaTraslados";
export { default as CrearTrasladoRetorno } from "../../components/formatos/TrasladosRetorno/TrasladosRetorno";
export { default as TrasladosRetornoLista } from "../../components/formatos/TrasladosRetorno/TrasladosRetornoLista";
